name: Code Pull Request
description: Submit code for review
title: "<gitmoji> <short description>"
labels: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to submit a code pull request for this project!
  - type: checkboxes
    id: code-of-conduct
    attributes:
      label: Code of Conduct
      description: Please read the code of conduct before proceeding.
      options:
        - label: I've read the [code of conduct](https://github.com/amuzil/.github/blob/main/.github/code-of-conduct.md) and wholeheartedly agree
          required: true
  - type: checkboxes
    id: contribution-guidelines
    attributes:
      label: Contribution Guidelines
      description: Please read the contribution guidelines before proceeding.
      options:
        - label: I've read the [contribution guidelines](https://github.com/amuzil/.github/blob/main/.github/contributing.md) and wholeheartedly agree
          required: true
  - type: checkboxes
    id: checklist
    attributes:
      label: I have a pull request and checked that…
      description: Make sure that your request fulfills all of the following requirements. If one requirement cannot be satisfied, explain in detail why.
      options:
      - label: my code is well-formatted and follows the project's code style
      - label: my code is well-documented where necessary
      - label: my code is well-tested and passes all tests
      - label: I have linked the relevant issue(s)/pull request(s) (if any) in the description
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please provide a brief description of the changes in 1-2 sentences.
    validations:
      required: true
  - type: textarea
    id: impact
    attributes:
      label: Impact
      description: Please describe the impact of your changes for other developers and users.
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Please provide any additional context or screenshots about the pull request.
    validations:
      required: false
  - type: checkboxes
    id: attachments
    attributes:
      label: Attachments
      description: Please attach any relevant files, such as screenshots, logs, configuration files, et cetera.
      options:
        - label: I've attached relevant files (if any)
          required: true
