title: "Should we <idea>?"
labels: ["Ideas"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to discuss a new idea for this project!
  - type: checkboxes
    id: code-of-conduct
    attributes:
      label: Code of Conduct
      description: Please read the code of conduct before proceeding.
      options:
        - label: I have read the [code of conduct](https://github.com/amuzil/.github/blob/main/.github/.github/code-of-conduct.md) and wholeheartedly agree
          required: true
  - type: checkboxes
    id: contribution-guidelines
    attributes:
      label: Contribution Guidelines
      description: Please read the contribution guidelines before proceeding.
      options:
        - label: I have read and understood the [contribution guidelines](https://github.com/amuzil/.github/blob/main/.github/.github/contributing.md)
          required: true
  - type: checkboxes
    id: checklist
    attributes:
      label: I have an idea and checked that…
      description: Make sure that your request fulfills all of the following requirements. If one requirement cannot be satisfied, explain in detail why.
      options:
      - label: the documentation does not mention my idea at all
      - label: there are no open or closed issues that are related to my idea
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please provide a brief description of the idea in 1-2 sentences.
    validations:
      required: true
  - type: textarea
    id: reasons
    attributes:
      label: Reasons
      description: Please describe the reasons why you think this idea is worth discussing.
    validations:
      required: true
  - type: textarea
    id: current-situation
    attributes:
      label: Current situation
      description: Please describe the current situation and how it could be improved.
      placeholder: |-
        Currently, …

        This could be improved by …
    validations:
      required: false
  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed solution
      description: Please describe the proposed solution.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives
      description: Please describe any alternative solutions you've considered.
    validations:
      required: false
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Please provide any additional context or screenshots about the idea here.
    validations:
      required: false
  - type: checkboxes
    id: attachments
    attributes:
      label: Attachments
      description: Please attach any relevant files, such as screenshots, logs, configuration files, et cetera.
      options:
        - label: I have attached relevant files (if any)
          required: true
